#Es el identificador de sonarqube
sonar.projectKey=adopcion-mascotas
#Es el nombre que se vera en el panel
sonar.projectName=AdoptaMe - Adopcion de Mascotas
#Indica donde esta el codigo a analizar
sonar.sources=src
#Indica donde estab las pruebas
sonar.tests=tests
#No analiza las imagenes debido a que no es codigo
sonar.exclusions=src/Img/**
#Es la codificacion de los archivos para que lea bien las letras especiales
sonar.sourceEncoding=UTF-8
